spring:
  datasource:
    password: caymaz
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
